package io.ezbook.api.model;

// Generated Sep 30, 2019 11:02:40 PM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private static final long serialVersionUID = 3660651733680541216L;
	private long id;
	private AccountCategory accountCategories;
	private BigDecimal creditBalance;
	private BigDecimal debtBalance;
	private String name;
	private BigDecimal totalBalance;

	public Account() {
	}

	public Account(long id) {
		this.id = id;
	}

	public Account(long id, AccountCategory accountCategories, BigDecimal creditBalance, BigDecimal debtBalance,
			String name, BigDecimal totalBalance) {
		this.id = id;
		this.accountCategories = accountCategories;
		this.creditBalance = creditBalance;
		this.debtBalance = debtBalance;
		this.name = name;
		this.totalBalance = totalBalance;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountCategoryId")
	@JsonBackReference
	public AccountCategory getAccountCategories() {
		return this.accountCategories;
	}

	public void setAccountCategories(AccountCategory accountCategories) {
		this.accountCategories = accountCategories;
	}

	@Column(name = "creditBalance")
	@JsonProperty("credit")
	public BigDecimal getCreditBalance() {
		return this.creditBalance;
	}

	public void setCreditBalance(BigDecimal creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Column(name = "debtBalance")
	@JsonProperty("debit")
	public BigDecimal getDebtBalance() {
		return this.debtBalance;
	}

	public void setDebtBalance(BigDecimal debtBalance) {
		this.debtBalance = debtBalance;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "totalBalance")
	@JsonProperty("total")
	public BigDecimal getTotalBalance() {
		return this.totalBalance;
	}

	public void setTotalBalance(BigDecimal totalBalance) {
		this.totalBalance = totalBalance;
	}

}
