package io.ezbook.api.model;
// Generated Sep 30, 2019 11:02:40 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AccountCategories generated by hbm2java
 */
@Entity
@Table(name = "account_category")
public class AccountCategory implements java.io.Serializable {

	private static final long serialVersionUID = 1138149679815707367L;
	private long id;
	private AccountType accountType;
	private String name;
	private Set<Account> accounts = new HashSet<Account>(0);

	public AccountCategory() {
	}

	public AccountCategory(long id, AccountType accountType, String name) {
		this.id = id;
		this.accountType = accountType;
		this.name = name;
	}

	public AccountCategory(long id, AccountType accountType, String name, Set<Account> accounts) {
		this.id = id;
		this.accountType = accountType;
		this.name = name;
		this.accounts = accounts;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountTypeId", nullable = false)
	@JsonManagedReference
	public AccountType getAccountType() {
		return this.accountType;
	}

	public void setAccountType(AccountType accountType) {
		this.accountType = accountType;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountCategories")
	@JsonManagedReference
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
