package io.ezbook.api.model;
// Generated Sep 30, 2019 11:02:40 PM by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * JournalDetail generated by hbm2java
 */
@Entity
@Table(name = "journal_detail")
public class JournalDetail implements java.io.Serializable {

	private static final long serialVersionUID = -4808758304212711781L;
	private long id;
	private Journal journal;
	private BigDecimal debt;
	private BigDecimal credit;
	private Long accountId;

	public JournalDetail() {
	}

	public JournalDetail(long id) {
		this.id = id;
	}

	public JournalDetail(long id, Journal journal, BigDecimal debt, BigDecimal credit, Long accountId) {
		this.id = id;
		this.journal = journal;
		this.debt = debt;
		this.credit = credit;
		this.accountId = accountId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "journalId")
	public Journal getJournal() {
		return this.journal;
	}

	public void setJournal(Journal journal) {
		this.journal = journal;
	}

	@Column(name = "debt", precision = 131089, scale = 0)
	public BigDecimal getDebt() {
		return this.debt;
	}

	public void setDebt(BigDecimal debt) {
		this.debt = debt;
	}

	@Column(name = "credit", precision = 131089, scale = 0)
	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	@Column(name = "accountId")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

}
