CREATE TABLE "account"(
    "id" BIGINT NOT NULL,
    "creditBalance" DECIMAL(19, 2),
    "debtBalance" DECIMAL(19, 2),
    "name" VARCHAR(255),
    "totalBalance" DECIMAL(19, 2),
    "accountCategoryId" BIGINT
);

CREATE TABLE "account_category"(
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "accountTypeId" BIGINT NOT NULL
);

CREATE TABLE "account_type"(
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "type" BOOLEAN NOT NULL
);


CREATE TABLE "journal"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_680D_47D0_A280_E330D8361BF9") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_680D_47D0_A280_E330D8361BF9",
    "date" DATE NOT NULL,
    "notes" VARCHAR(255),
    "status" INTEGER
);

CREATE TABLE "journal_detail"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2E663758_41D1_4F8D_BA70_6A7593611327") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2E663758_41D1_4F8D_BA70_6A7593611327",
    "accountId" BIGINT,
    "credit" DECIMAL(131089, 0),
    "debt" DECIMAL(131089, 0),
    "journalId" BIGINT
);

ALTER TABLE "account" ADD CONSTRAINT "CONSTRAINT_B" PRIMARY KEY("id");
ALTER TABLE "account_category" ADD CONSTRAINT "CONSTRAINT_3" PRIMARY KEY("id");
ALTER TABLE "account_type" ADD CONSTRAINT "CONSTRAINT_4" PRIMARY KEY("id");
ALTER TABLE "journal" ADD CONSTRAINT "CONSTRAINT_A" PRIMARY KEY("id");
ALTER TABLE "journal_detail" ADD CONSTRAINT "CONSTRAINT_D" PRIMARY KEY("id");