SET IGNORECASE 1;

CREATE SEQUENCE "SYSTEM_SEQUENCE_A649BE84_B443_46D6_8100_95E818414F39" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "SYSTEM_SEQUENCE_5D6A6CED_114C_4C6D_ACA3_25CF7714F097" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "SYSTEM_SEQUENCE_FFE6A045_E955_4DD9_9ED9_EDDB5527C76E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "SYSTEM_SEQUENCE_2AB730D7_38B6_4A25_BBBD_C170AC6A2A7D" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "SYSTEM_SEQUENCE_071CFBF0_EF1E_4E28_B2CE_5BB65D0B125F" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "SYSTEM_SEQUENCE_C1EDF288_6D09_47C3_AD5E_C2FBA5FECFCC" START WITH 1 BELONGS_TO_TABLE;
CREATE TABLE "account"
(
    "id"            BIGINT NOT NULL,
    "accountType"   INTEGER,
    "creditBalance" DOUBLE,
    "debtBalance"   DOUBLE,
    "name"          VARCHAR_IGNORECASE(255),
    "isUserDefined" BOOLEAN,
    "parentId"      BIGINT
);
ALTER TABLE "account"
    ADD CONSTRAINT "CONSTRAINT_B" PRIMARY KEY ("id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.account;
CREATE TABLE "customer"
(
    "id"           BIGINT DEFAULT (NEXT VALUE FOR "SYSTEM_SEQUENCE_A649BE84_B443_46D6_8100_95E818414F39") NOT NULL NULL_TO_DEFAULT SEQUENCE "SYSTEM_SEQUENCE_A649BE84_B443_46D6_8100_95E818414F39",
    "address"      VARCHAR_IGNORECASE(255),
    "company"      VARCHAR_IGNORECASE(255),
    "emailAddress" VARCHAR_IGNORECASE(255),
    "name"         VARCHAR_IGNORECASE(255),
    "phoneNumber"  VARCHAR_IGNORECASE(255)
);
ALTER TABLE "customer"
    ADD CONSTRAINT "CONSTRAINT_2" PRIMARY KEY ("id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.customer;
CREATE TABLE "journal"
(
    "id"     BIGINT DEFAULT (NEXT VALUE FOR "SYSTEM_SEQUENCE_2AB730D7_38B6_4A25_BBBD_C170AC6A2A7D") NOT NULL NULL_TO_DEFAULT SEQUENCE "SYSTEM_SEQUENCE_2AB730D7_38B6_4A25_BBBD_C170AC6A2A7D",
    "date"   DATE                                                                                   NOT NULL,
    "notes"  VARCHAR_IGNORECASE(255),
    "status" INTEGER
);
ALTER TABLE "journal"
    ADD CONSTRAINT "CONSTRAINT_A" PRIMARY KEY ("id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.journal;
CREATE TABLE "journal_detail"
(
    "id"        BIGINT DEFAULT (NEXT VALUE FOR "SYSTEM_SEQUENCE_FFE6A045_E955_4DD9_9ED9_EDDB5527C76E") NOT NULL NULL_TO_DEFAULT SEQUENCE "SYSTEM_SEQUENCE_FFE6A045_E955_4DD9_9ED9_EDDB5527C76E",
    "accountId" BIGINT,
    "credit"    DOUBLE,
    "debt"      DOUBLE,
    "journalId" BIGINT
);
ALTER TABLE "journal_detail"
    ADD CONSTRAINT "CONSTRAINT_D" PRIMARY KEY ("id");

CREATE TABLE "product"
(
    "id"          BIGINT DEFAULT (NEXT VALUE FOR "SYSTEM_SEQUENCE_C1EDF288_6D09_47C3_AD5E_C2FBA5FECFCC") NOT NULL NULL_TO_DEFAULT SEQUENCE "SYSTEM_SEQUENCE_C1EDF288_6D09_47C3_AD5E_C2FBA5FECFCC",
    "description" VARCHAR_IGNORECASE(255),
    "name"        VARCHAR_IGNORECASE(255),
    "price"       DOUBLE
);
ALTER TABLE "product"
    ADD CONSTRAINT "CONSTRAINT_E" PRIMARY KEY ("id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.product;

ALTER TABLE "account"
    ADD CONSTRAINT "FKrekid6sjpksp58m22flmfwc4m" FOREIGN KEY ("parentId") REFERENCES "account" ("id") NOCHECK;
ALTER TABLE "journal_detail"
    ADD CONSTRAINT "FKc9omyrc8ryfcjptnklxr3m821" FOREIGN KEY ("journalId") REFERENCES "journal" ("id") NOCHECK;
