CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_680D_47D0_A280_E330D8361BF9" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2E663758_41D1_4F8D_BA70_6A7593611327" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_A00D_821F_C761_E330D83OL281" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_XJ81_740S_U0431_E330D83OJ872" START WITH 1 BELONGS_TO_TABLE;


CREATE TABLE "PUBLIC"."role"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_XJ81_740S_U0431_E330D83OJ872") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_XJ81_740S_U0431_E330D83OJ872",
    "description" VARCHAR(255),
    "role_name" VARCHAR(255)
);

CREATE TABLE "PUBLIC"."user"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_A00D_821F_C761_E330D83OL281") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_A00D_821F_C761_E330D83OL281",
    "first_name" VARCHAR(255),
    "last_name" VARCHAR(255),
    "password" VARCHAR(255),
    "tenant_id" VARCHAR(255),
    "username" VARCHAR(255)
);

CREATE TABLE "PUBLIC"."user_role"(
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL
);

CREATE TABLE "PUBLIC"."account"(
    "id" BIGINT NOT NULL,
    "creditBalance" DECIMAL(19, 2),
    "debtBalance" DECIMAL(19, 2),
    "name" VARCHAR(255),
    "totalBalance" DECIMAL(19, 2),
    "accountCategoryId" BIGINT
);

CREATE TABLE "PUBLIC"."account_category"(
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "accountTypeId" BIGINT NOT NULL
);

CREATE TABLE "PUBLIC"."account_type"(
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "type" BOOLEAN NOT NULL
);

CREATE TABLE "PUBLIC"."journal"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_680D_47D0_A280_E330D8361BF9") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95A8DFFC_680D_47D0_A280_E330D8361BF9",
    "date" DATE NOT NULL,
    "notes" VARCHAR(255),
    "status" INTEGER
);

CREATE TABLE "PUBLIC"."journal_detail"(
    "id" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2E663758_41D1_4F8D_BA70_6A7593611327") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2E663758_41D1_4F8D_BA70_6A7593611327",
    "accountId" BIGINT,
    "credit" DECIMAL(131089, 0),
    "debt" DECIMAL(131089, 0),
    "journalId" BIGINT
);


ALTER TABLE "PUBLIC"."role" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_35" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."user" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_36" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."account" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."account_category" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."account_type" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."journal" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("id");
ALTER TABLE "PUBLIC"."journal_detail" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("id");

ALTER TABLE "PUBLIC"."account" ADD CONSTRAINT "PUBLIC"."FKfplih8v4q1y7b2tdvxh8jwd9p" FOREIGN KEY("accountCategoryId") REFERENCES "PUBLIC"."account_category"("id") NOCHECK;
ALTER TABLE "PUBLIC"."journal_detail" ADD CONSTRAINT "PUBLIC"."FKc9omyrc8ryfcjptnklxr3m821" FOREIGN KEY("journalId") REFERENCES "PUBLIC"."journal"("id") NOCHECK;
ALTER TABLE "PUBLIC"."user_role" ADD CONSTRAINT "PUBLIC"."FKka3w3atry4amefp94rblb52n7" FOREIGN KEY("role_id") REFERENCES "PUBLIC"."role"("id") NOCHECK;
ALTER TABLE "PUBLIC"."account_category" ADD CONSTRAINT "PUBLIC"."FKnxrytkybfyyya1a1l46cewj6j" FOREIGN KEY("accountTypeId") REFERENCES "PUBLIC"."account_type"("id") NOCHECK;
ALTER TABLE "PUBLIC"."user_role" ADD CONSTRAINT "PUBLIC"."FKhjx9nk20h4mo745tdqj8t8n9d" FOREIGN KEY("user_id") REFERENCES "PUBLIC"."user"("id") NOCHECK;
